### ISSUE TITLE
Add an game option in which players write a word as their first step

### ISSUE THREAD

**Issue by tannerkrewson** [tannerkrewson/drawphone#1]
Thanks [/u/Bobius](https://www.reddit.com/user/Bobius):

https://www.reddit.com/r/boardgames/comments/7lhj20/a_year_ago_i_was_wondering_why_there_were_no/drmbqrd/

**Comment by SomeAwesomeGuy** [comment]
I'd also like to suggest having the ability to write more than a single word. Absurdly descriptive prompts leads to much funnier chains.

**Comment by tannerkrewson** [comment]
@SomeAwesomeGuy that's the plan! I'm working on it now, and players should be able to add as few or as many words as they want.

**Comment by tannerkrewson** [comment]
Finished! Will be apart of the next update.

**Comment by tannerkrewson** [comment]
Should be live now #8
