### ISSUE TITLE
Undo button for drawing

### ISSUE THREAD

**Issue by tannerkrewson** [tannerkrewson/drawphone#2]
Thanks [/u/Trenzor](https://www.reddit.com/user/Trenzor):
https://www.reddit.com/r/boardgames/comments/7lhj20/a_year_ago_i_was_wondering_why_there_were_no/drmj4dn/

**Comment by tannerkrewson** [comment]
I'm not sure if this is simple/possible with canvas.js. Need to look into it.

**Comment by philip-n** [comment]
An easy-to-implement shortcut might be an eraser option (a.k.a. just draw in the colour of the background)?

**Comment by tannerkrewson** [comment]
@philip-n You're right. My concern is that it would be difficult to convey erasing on a touch screen. So, I'm going to give Undo a shot first.

**Comment by tannerkrewson** [comment]
Hey, I actually got it to work~!

**Comment by tannerkrewson** [comment]
Should be live now #8
