### ISSUE TITLE
Add Telestrations word bank

### ISSUE THREAD

**Issue by beamer159** [tannerkrewson/drawphone#24]
Drawphone is similar to the board game Telestrations, so players familiar with Telestrations may want to play with that game's word bank. An additional advantage is that the Telestrations word bank is about 4 times bigger than the existing Pictionary word bank (~2000 words vs ~500 words), resulting in fewer duplicate words across multiple games.

**Comment by tannerkrewson** [comment]
good idea; more words is always better. can't find a list on the web tho :/
