### ISSUE TITLE
Show name of player whose drawing/guess you are receiving

### ISSUE THREAD

**Issue by cudzinovica** [tannerkrewson/drawphone#40]
In real life telestrations, you hand your booklet off to the next person to guess your drawing or draw your guess. So you know who is handing off the drawing/guess to you. Having this knowledge in drawphone is important because if you are given a really ridiculous guess or indecipherable drawing, you need to know who you can blame immediately.

**Comment by tannerkrewson** [comment]
Good point! I think this should be an option that can be selected before the game is started
