### ISSUE TITLE
Option to add bot if a player leaves?

### ISSUE THREAD

**Issue by DoctorBracewell** [tannerkrewson/drawphone#51]
Perhaps an option to replace a player that's left with a bot could be helpful, especially if you're right at the end of a game.

**Comment by tannerkrewson** [comment]
GREAT idea. thanks! i also gotta try and fix the bots too. 👍 👍

**Comment by tannerkrewson** [comment]
done in 4f4b693032ff8fbc60868ec4a5b5a9916e4cd32d might be a week or two before the feature goes live 👍
