### ISSUE TITLE
Current options not shown when new player joins

### ISSUE THREAD

**Issue by DoctorBracewell** [tannerkrewson/drawphone#64]
https://github.com/tannerkrewson/drawphone/pull/52
When new players join the game changed settings aren't shown.

When the admin changes settings they're mirrored on the players that are currently in the game, but if another player joins after settings have been changed the new player will have the default settings rather than the game ones.

Basically send the current settings to the player who joined and show on their screen.

**Comment by tannerkrewson** [comment]
oops. this might have been fixed in 0d595e5512ea26202b08c0e07f038305a9743c2d but i dont remember
