### ISSUE TITLE
[Feature Suggestion] PWA (Progressive Web App)

### ISSUE THREAD

**Issue by deanilvincent** [tannerkrewson/drawphone#66]
Hi,

Drawphone is an amazing application :) Hopefully, there will be PWA feature in the future like "Add to Homescreen."

**Comment by tannerkrewson** [comment]
thanks for your suggestion; i completely agree. I've done this in spyfall, but i'm going to remove it, and not implement it for drawphone, in favor of adding the functionality to [rocketcrab](https://github.com/tannerkrewson/rocketcrab) 👍

**Comment by tannerkrewson** [comment]
dupe of #35
