### ISSUE TITLE
add an option to limit the amount of rounds if there are a lot of players

### ISSUE THREAD

**Issue by antolabarca** [tannerkrewson/drawphone#69]
I just played with 24 people and it took forever, it would have been nice to have the option to limit the rounds to 10 or something like that

**Comment by tannerkrewson** [comment]
good idea! wonder how hard that would be 🤔 

fun fact, according to my analytics, the largest drawphone game ever played was 42 players! legend has it, they haven't even finished it yet 😆

**Comment by antolabarca** [comment]
😆

how do you calculate the amount of rounds at the beginning of a game now?

**Comment by themooingpig** [comment]
Hi, we just played a game today with 22 people and it was rough. We ended up having to just skip after the fifth round. +1 on feature request.

**Comment by tannerkrewson** [comment]
done in e97374247bc8dd899ad0abc22d55edebc9f2f2ff 3ea305d8b6a6e9d627ea2278d160cf320ee40f87 664fdbd5472a21290dd8edd5ca3b1741010f46ad 1ba2acbf01c003e484205414d7f48d2af16466f1 38ce6d5f89d1896f3bfec7ba2b709e6a515ef503

this feature is not live yet, but should be in the next few weeks 👍 

preview:
![Capture](https://user-images.githubusercontent.com/8444595/108117965-4a90aa00-7063-11eb-8469-2aacab0c67c8.PNG)
