### ISSUE TITLE
Archive shows a lot of "false" strings

### ISSUE THREAD

**Issue by Skasi** [tannerkrewson/drawphone#83]
![grafik](https://user-images.githubusercontent.com/132906/98308692-f9374000-1fc8-11eb-8e10-59177b9e495e.png)
The archive on https://drawphone.tannerkrewson.com/archive shows "false" for some words. This happens for the last four rounds I played (out of ten) and only ever happens for the initial starting word, never for the final word.

**Comment by tannerkrewson** [comment]
thanks for report, done in 68cd52ddb881f239d007d0f37f957fbcf96c8343 awaiting push to prod
