### ISSUE TITLE
Clarify the maximum number of players

### ISSUE THREAD

**Issue by rjchee** [tannerkrewson/drawphone#84]
It doesn't seem like the game says what the maximum number of players is in the How to Play section of the website. From peeking a the code a bit, it doesn't seem like there is a limit (besides possibly what the server can handle). Could this be clarified on the website? I think it would help people with large groups decide whether or not this game can work for them.

**Comment by MJFruits** [comment]
It states that "Drawphone has no max player limit!"

**Comment by rjchee** [comment]
Great! That message wasn't there when I opened this issue. Closing.
